version: 0.2
env:
  variables:
    REGION: us-east-1
    VERSION: "1"
  parameter-store:
    AWS_ACCOUNT_ID: /custom-scraping/aws_account_id

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing runtime..."

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - chmod +x $CODEBUILD_SRC_DIR/deploy.sh

  build:
    commands:
      - echo "Starting build..."
      - $CODEBUILD_SRC_DIR/deploy.sh $AWS_ACCOUNT_ID
