version: 0.2
env:
  variables:
    REGION: us-east-1
    VERSION: "1"
  parameter-store:
    AWS_ACCOUNT_ID: /custom-scraping/aws_account_id

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 20
    commands: []
    
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Installing dependencies..."
      - npm install
      - chmod +x $CODEBUILD_SRC_DIR/deploy.sh
      - echo "AWS Account ID: $AWS_ACCOUNT_ID"
      
  build:
    on-failure: ABORT
    commands:
      - echo "Building..."
      - $CODEBUILD_SRC_DIR/deploy.sh $AWS_ACCOUNT_ID
