version: 0.2
env:
  variables:
    REGION: us-east-1
    VERSION: "1"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase started"

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - chmod +x $CODEBUILD_SRC_DIR/deploy.sh

  build:
    commands:
      - echo "Building..."
      - $CODEBUILD_SRC_DIR/deploy.sh

